name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd='curl -sS http://localhost:9000/api/system/health | grep -q '"'"'"UP"'"'"' || exit 1'
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Wait for SonarQube to be ready
        run: |
          echo "Waiting for SonarQube to be ready..."
          until curl -sS http://localhost:9000/api/system/health | grep -q "UP"; do
            echo "SonarQube is not ready yet. Retrying in 5 seconds..."
            sleep 5
          done
          echo "SonarQube is ready."

      - name: Install SonarQube scanner
        run: npm install -g sonar-scanner

      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sonar-github \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
